global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "docker-metrics"
    static_configs:
      - targets: ["localhost:9090"]  

  - job_name: "lgbm-api"
    static_configs:
      - targets: ["17.42.69.76:5001"]  
